# --- Базовые настройки игры ---
TILE_SIZE = 64          
MAP_WIDTH = 60          # БОЛЬШАЯ карта (было 20)
MAP_HEIGHT = 60         # БОЛЬШАЯ карта (было 15)

# Фиксированный размер окна (меньше карты, чтобы был скроллинг)
SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768     # Включает 60 пикселей под интерфейс внизу

SCREEN_TITLE = "Герои Меча и Магии: Бесконечное Королевство"

# --- Типы ландшафта ---
TERRAIN_GRASS = 0
TERRAIN_MOUNTAIN = 1  
TERRAIN_WATER = 2     
TERRAIN_FOREST = 3    

# --- Цвета ---
COLOR_GRASS = (34, 139, 34)
COLOR_GRASS_DETAIL = (20, 100, 20)
COLOR_MOUNTAIN = (105, 105, 105)
COLOR_MOUNTAIN_PEAK = (240, 240, 240)
COLOR_WATER = (30, 144, 255)
COLOR_WATER_WAVE = (135, 206, 250)
COLOR_FOREST = (0, 100, 0)
COLOR_GRID = (0, 0, 0, 30)
COLOR_GOLD = (255, 215, 0)
COLOR_POTION = (0, 255, 127)
COLOR_UI_BG = (40, 40, 40)

# --- Параметры героя ---
HERO_START_GOLD = 350
HERO_START_HP = 120
HERO_ATTACK = 12
HERO_DEFENSE = 6

# --- Параметры врагов (6 типов с шансами спавна) ---
ENEMY_WOLF_HP = 30; ENEMY_WOLF_ATTACK = 14; ENEMY_WOLF_DEFENSE = 1; ENEMY_WOLF_CHANCE = 0.25
ENEMY_GOBLIN_HP = 40; ENEMY_GOBLIN_ATTACK = 10; ENEMY_GOBLIN_DEFENSE = 3; ENEMY_GOBLIN_CHANCE = 0.25
ENEMY_SKELETON_HP = 55; ENEMY_SKELETON_ATTACK = 16; ENEMY_SKELETON_DEFENSE = 4; ENEMY_SKELETON_CHANCE = 0.20
ENEMY_LICH_HP = 50; ENEMY_LICH_ATTACK = 24; ENEMY_LICH_DEFENSE = 2; ENEMY_LICH_CHANCE = 0.15
ENEMY_GOLEM_HP = 130; ENEMY_GOLEM_ATTACK = 18; ENEMY_GOLEM_DEFENSE = 10; ENEMY_GOLEM_CHANCE = 0.10
ENEMY_DRAGON_HP = 220; ENEMY_DRAGON_ATTACK = 28; ENEMY_DRAGON_DEFENSE = 8; ENEMY_DRAGON_CHANCE = 0.05

# --- Новые враги ---
ENEMY_ORC_HP = 65; ENEMY_ORC_ATTACK = 18; ENEMY_ORC_DEFENSE = 5; ENEMY_ORC_CHANCE = 0.15
ENEMY_TROLL_HP = 160; ENEMY_TROLL_ATTACK = 20; ENEMY_TROLL_DEFENSE = 6; ENEMY_TROLL_CHANCE = 0.08
ENEMY_VAMPIRE_HP = 85; ENEMY_VAMPIRE_ATTACK = 22; ENEMY_VAMPIRE_DEFENSE = 4; ENEMY_VAMPIRE_CHANCE = 0.07
ENEMY_DEMON_HP = 110; ENEMY_DEMON_ATTACK = 30; ENEMY_DEMON_DEFENSE = 5; ENEMY_DEMON_CHANCE = 0.05
ENEMY_BANDIT_HP = 45; ENEMY_BANDIT_ATTACK = 16; ENEMY_BANDIT_DEFENSE = 3; ENEMY_BANDIT_CHANCE = 0.12
ENEMY_DARK_ELF_HP = 60; ENEMY_DARK_ELF_ATTACK = 21; ENEMY_DARK_ELF_DEFENSE = 4; ENEMY_DARK_ELF_CHANCE = 0.06
ENEMY_GIANT_HP = 190; ENEMY_GIANT_ATTACK = 24; ENEMY_GIANT_DEFENSE = 7; ENEMY_GIANT_CHANCE = 0.04
ENEMY_PHOENIX_HP = 130; ENEMY_PHOENIX_ATTACK = 26; ENEMY_PHOENIX_DEFENSE = 3; ENEMY_PHOENIX_CHANCE = 0.03




ENEMY_WOLF_COUNT = 5
ENEMY_GOBLIN_COUNT = 7
ENEMY_SKELETON_COUNT = 5
ENEMY_LICH_COUNT = 4
ENEMY_GOLEM_COUNT = 4
ENEMY_DRAGON_COUNT = 2

# --- Параметры ресурсов (увеличены для большой карты) ---
POTION_COUNT = 25
POTION_HEAL_AMOUNT = 40
GOLD_COUNT = 30
GOLD_PER_PILE = 60

GOLD_SPAWN_PER_WEEK = 5     
POTION_SPAWN_PER_WEEK = 3   
ENEMIES_SPAWN_PER_WEEK = 4  

# --- Опыт и уровни ---
XP_PER_KILL = 60
XP_TO_LEVEL_UP = 120
LEVEL_UP_HP_BONUS = 25
LEVEL_UP_STAT_BONUS = 3

# --- Поведение врагов и сложность ---
ENEMY_AGGRO_RANGE = 1  
ENEMY_SCALING_PER_WEEK = 0.18  # Было 0.15 (теперь 18% рост)
ENEMY_DAMAGE_SCALING = 0.12    # НОВОЕ: +12% урона за неделю
# --- Система времени ---
TURNS_PER_DAY = 10           
DAYS_PER_WEEK = 7           
TURNS_PER_WEEK = 70         
WEEKS_TO_WIN = 10           

# --- Стоимость улучшений ---
UPGRADE_ATTACK_COST = 200      # Было 120
UPGRADE_DEFENSE_COST = 200     # Было 120
UPGRADE_HP_COST = 300          # Было 180
UPGRADE_AMOUNT = 5

# Лимиты улучшений
MAX_ATTACK = 50
MAX_DEFENSE = 35
MAX_HP = 600

